tools:
  node:
    version: latest
    
  erlang:
    version: latest
    env:
      KERL_CONFIGURE_OPTIONS: "--enable-wx"
      
  elixir:
    version: latest
    
  usage:
    version: latest

dependencies:
  arch:
    - jdk-openjdk
    - unixodbc
    - ncurses
    - libssh
    - wxwidgets-gtk3
    - wxwidgets-common
    - unzip
    
  darwin:
    - openjdk
    - unixodbc
