arch:
  laptop:
    services:
      - name: thermald
        package: thermald
        enable: true
      - name: acpid
        package: acpi
        enable: true
      - name: auto-cpufreq
        package: auto-cpufreq
        enable: true
        config_src: .cp/auto-cpufreq.conf
        config_dest: /etc/auto-cpufreq.conf
    firmware:
      package: fwupd
      timer: fwupd-refresh.timer
    microcode:
      package: intel-ucode
    fingerprint:
      package: fprintd
      pam_files:
        - src: .cp/pam.d/system-local-login
          dest: /etc/pam.d/system-local-login
        - src: .cp/pam.d/polkit-1
          dest: /etc/pam.d/polkit-1
      interactive_setup: true
    logind:
      config_dir: .cp/systemd/logind.conf.d
      dest_dir: /etc/systemd/logind.conf.d
  firewall:
    package: ufw
    service: ufw
    enable: true
    rules:
      - default deny incoming
      - default allow outgoing
darwin:
  services: []
