common:
  essential:
    - stow
    - git
    - curl
    
  shell:
    - neovim
    - bat
    - eza
    - zoxide
    - fzf
    - fd
    - bottom
    - ripgrep
    - jq
    - yazi
    - oh-my-posh
    - fastfetch
    
  dev:
    - lazygit
    - lazydocker
    - docker
    - just
    - mise
    - 1password-cli
    - shellcheck
    - shfmt
    
  terminals:
    - tmux
    - ghostty
    - kitty

arch:
  packages:
    - usbutils
    - wl-clipboard
    - cliphist
    
  fonts:
    - ttf-dejavu
    - ttf-liberation
    - noto-fonts
    - noto-fonts-emoji
    
  nerd_fonts:
    - otf-commit-mono-nerd
    - otf-geist-mono-nerd
    - ttf-ibmplex-mono-nerd
    
  aur:
    - opencode-bin
    - helium-browser-bin
    - 1password
    - spotify
    - soteria-git
    - impala
    - vicinae-bin

darwin:
  brew: []
  cask: []

nerd_fonts:
  - CommitMono
  - GeistMono
  - JetBrainsMono
  - FiraCode
